on: 
  schedule:
    - cron: "0 20 * * *"
jobs:
  # As the pgvecto-rs module is needed in the Immich Postgres, a custom Bitnami Image Build is implemented.
  build-postgres:
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}/pg-bitnami-vecto-rs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get vars
        run: ./get_vars.sh
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Get bitnami tag
        run: cd ./images/pgvecto-bitnami && ./bitnami-tag.sh >> $GITHUB_ENV
      - name: Build and Push Versioned Docker Image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./images/pgvecto-bitnami/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BITNAMI_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BITNAMI_TAG=${{ env.BITNAMI_TAG }}