on:
    schedule:
        - cron: "0 20 * * *"
    push:
        branches:
            - "main"
    workflow_dispatch:
        inputs:
            pg_version:
                description: "PostgreSQL major version"
                required: true
                default: "17"
                type: string

jobs:
    build-postgres:
        env:
            REGISTRY: ghcr.io
            REPO_NAME: ${{ github.repository }}
            PG_MAJOR_VERSION: ${{ inputs.pg_version || '17' }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Get variables
              id: get_vars
              run: ./get_vars.sh

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  build-args: |
                      BITNAMI_NAME=${{ env.BITNAMI_NAME }}
                      PGVECTOR_NAME=${{ env.PGVECTOR_NAME }}
                  tags: |
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:${{ env.TAG_IDENTIFIER }}
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:pg${{ env.PG_MAJOR_VERSION }}
                      ${{ env.REGISTRY }}/${{ env.REPO_NAME }}:latest
